### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by kwinwithak** [tututwo/climate-trace-scrolly#1]
Hi Gordon. I set up the hosting for this at https://labs.climatetrace.org/landfill/ and figured it would be easier to interact with you here instead of forcing Eric to be the middleman for our communication.

The hosting at labs.climatetrace.org is a bucket with "Static website hosting" turned on and cloudfront pointed at it. We want the option of hosting other apps in this bucket, so the `/landfill` path is necessary to keep this app separate from the others. 

I synced your latest commits to my fork repo, but it looks like there are still some routing issues:

1. https://climate-trace-scrolly.vercel.app/ redirects to https://climate-trace-scrolly.vercel.app/landfill/, but if you go directly to https://climate-trace-scrolly.vercel.app/landfill/ it 404s.
2. The assets folder and climate-trace.svg are still relative to the root. Could make it work so that they're relative to `/landfill`, like `HOSTNAME://landfill/assets/...` and HOSTNAME://landfill/climate-trace.svg`

**Comment by tututwo** [comment]
It's a vercel issue, and should be resolved now. Let me know!

**Comment by kwinwithak** [comment]
The second issue isn't resolved:
<img width="813" alt="asset_path" src="https://github.com/user-attachments/assets/f75ed8cf-d025-441c-b9f6-76c838d1b172">
The files need to load from https://climate-trace-scrolly.vercel.app/landfill/assets/ instead of https://climate-trace-scrolly.vercel.app/assets/. 

I deployed the latest code here https://labs.climatetrace.org/landfill/. As you can see, it's not working because the build files are hosted at `s3://BUCKET/landfill/...` as opposed to `s3://BUCKET/'. I can temporarily work around this by copying the build files to the root of the bucket, but then we can't host any other apps in that bucket.
